sandbox/sail: Fixes the missing constructor error.
Fixes how the po object is constructed @ util/parse-options.h:240:16.

util/parse-options.h:240:16: error: no matching constructor for
initialization of 'kaldi::ParseOptions'
  ParseOptions po;

git-svn-id: http://svn.code.sf.net/p/kaldi/code@3704 5e6a8d80-dfce-4ca6-a32a-6e07a63d50c8